name: CI/CD Pipeline - Economia Brasil News

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/economia-brasil-news:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted # Usando o self-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          sed -i "s|__IMAGE_NAME__|${{ secrets.DOCKER_HUB_USERNAME }}/economia-brasil-news:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml

